version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-admin
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  api:
    build: .
    container_name: api-siteexpres
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=${POSTGRES_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

